/* Generated By:JavaCC: Do not edit this line. ParserCSS30TreeConstants.java Version 6.1_2 */
package com.helger.css.parser;

public interface ParserCSS30TreeConstants
{
  public int JJTVOID = 0;
  public int JJTERRORSKIPTO = 1;
  public int JJTROOT = 2;
  public int JJTURL = 3;
  public int JJTFUNCTION = 4;
  public int JJTMATHUNIT = 5;
  public int JJTMATHPRODUCTOPERATOR = 6;
  public int JJTMATHPRODUCT = 7;
  public int JJTMATHSUMOPERATOR = 8;
  public int JJTMATH = 9;
  public int JJTEXPRTERM = 10;
  public int JJTEXPROPERATOR = 11;
  public int JJTEXPR = 12;
  public int JJTCHARSETRULE = 13;
  public int JJTIMPORTRULE = 14;
  public int JJTNAMESPACERULEPREFIX = 15;
  public int JJTNAMESPACERULEURL = 16;
  public int JJTNAMESPACERULE = 17;
  public int JJTNAMESPACEPREFIX = 18;
  public int JJTELEMENTNAME = 19;
  public int JJTHASH = 20;
  public int JJTCLASS = 21;
  public int JJTATTRIBOPERATOR = 22;
  public int JJTATTRIBVALUE = 23;
  public int JJTATTRIB = 24;
  public int JJTNTH = 25;
  public int JJTPSEUDO = 26;
  public int JJTNEGATION = 27;
  public int JJTSELECTORCOMBINATOR = 28;
  public int JJTSELECTOR = 29;
  public int JJTPROPERTY = 30;
  public int JJTIMPORTANT = 31;
  public int JJTSTYLEDECLARATION = 32;
  public int JJTSTYLEDECLARATIONLIST = 33;
  public int JJTSTYLERULE = 34;
  public int JJTMEDIAMODIFIER = 35;
  public int JJTMEDIUM = 36;
  public int JJTMEDIAFEATURE = 37;
  public int JJTMEDIAEXPR = 38;
  public int JJTMEDIAQUERY = 39;
  public int JJTMEDIALIST = 40;
  public int JJTMEDIARULE = 41;
  public int JJTPSEUDOPAGE = 42;
  public int JJTPAGERULE = 43;
  public int JJTFONTFACERULE = 44;
  public int JJTKEYFRAMESIDENTIFIER = 45;
  public int JJTSINGLEKEYFRAMESELECTOR = 46;
  public int JJTKEYFRAMESSELECTOR = 47;
  public int JJTKEYFRAMESRULE = 48;
  public int JJTVIEWPORTRULE = 49;
  public int JJTSUPPORTSCONDITIONINPARENS = 50;
  public int JJTSUPPORTSNEGATION = 51;
  public int JJTSUPPORTSCONDITIONOPERATOR = 52;
  public int JJTSUPPORTSCONDITION = 53;
  public int JJTSUPPORTSRULE = 54;
  public int JJTUNKNOWNRULEPARAMETERLIST = 55;
  public int JJTUNKNOWNRULEBODY = 56;
  public int JJTUNKNOWNRULE = 57;
  public int JJTINVALID = 58;


  public String[] jjtNodeName = {
    "void",
    "errorSkipTo",
    "Root",
    "url",
    "function",
    "mathUnit",
    "mathProductOperator",
    "mathProduct",
    "mathSumOperator",
    "math",
    "exprTerm",
    "exprOperator",
    "expr",
    "charsetRule",
    "importRule",
    "namespaceRulePrefix",
    "namespaceRuleURL",
    "namespaceRule",
    "namespacePrefix",
    "elementName",
    "hash",
    "Class",
    "attribOperator",
    "attribValue",
    "attrib",
    "nth",
    "pseudo",
    "negation",
    "selectorCombinator",
    "selector",
    "property",
    "important",
    "styleDeclaration",
    "styleDeclarationList",
    "styleRule",
    "mediaModifier",
    "medium",
    "mediaFeature",
    "mediaExpr",
    "mediaQuery",
    "mediaList",
    "mediaRule",
    "pseudoPage",
    "pageRule",
    "fontfaceRule",
    "keyframesIdentifier",
    "singleKeyframeSelector",
    "keyframesSelector",
    "keyframesRule",
    "viewportRule",
    "supportsConditionInParens",
    "supportsNegation",
    "supportsConditionOperator",
    "supportsCondition",
    "supportsRule",
    "unknownRuleParameterList",
    "unknownRuleBody",
    "unknownRule",
    "invalid",
  };
}
/* JavaCC - OriginalChecksum=2794b6fe4156e5330cc57034ecebbfbb (do not edit this line) */
