/* Generated By:JavaCC: Do not edit this line. ParserCSS21TreeConstants.java Version 6.1_2 */
package com.helger.css.parser;

public interface ParserCSS21TreeConstants
{
  public int JJTVOID = 0;
  public int JJTERRORSKIPTO = 1;
  public int JJTROOT = 2;
  public int JJTURL = 3;
  public int JJTFUNCTION = 4;
  public int JJTEXPRTERM = 5;
  public int JJTEXPROPERATOR = 6;
  public int JJTEXPR = 7;
  public int JJTCHARSETRULE = 8;
  public int JJTIMPORTRULE = 9;
  public int JJTNAMESPACERULEPREFIX = 10;
  public int JJTNAMESPACERULEURL = 11;
  public int JJTNAMESPACERULE = 12;
  public int JJTNAMESPACEPREFIX = 13;
  public int JJTELEMENTNAME = 14;
  public int JJTHASH = 15;
  public int JJTCLASS = 16;
  public int JJTATTRIBOPERATOR = 17;
  public int JJTATTRIBVALUE = 18;
  public int JJTATTRIB = 19;
  public int JJTPSEUDO = 20;
  public int JJTSELECTORCOMBINATOR = 21;
  public int JJTSELECTOR = 22;
  public int JJTPROPERTY = 23;
  public int JJTIMPORTANT = 24;
  public int JJTSTYLEDECLARATION = 25;
  public int JJTSTYLEDECLARATIONLIST = 26;
  public int JJTSTYLERULE = 27;
  public int JJTMEDIUM = 28;
  public int JJTMEDIALIST = 29;
  public int JJTMEDIARULE = 30;
  public int JJTPSEUDOPAGE = 31;
  public int JJTPAGERULE = 32;
  public int JJTUNKNOWNRULEPARAMETERLIST = 33;
  public int JJTUNKNOWNRULEBODY = 34;
  public int JJTUNKNOWNRULE = 35;
  public int JJTINVALID = 36;


  public String[] jjtNodeName = {
    "void",
    "errorSkipTo",
    "Root",
    "url",
    "function",
    "exprTerm",
    "exprOperator",
    "expr",
    "charsetRule",
    "importRule",
    "namespaceRulePrefix",
    "namespaceRuleURL",
    "namespaceRule",
    "namespacePrefix",
    "elementName",
    "hash",
    "Class",
    "attribOperator",
    "attribValue",
    "attrib",
    "pseudo",
    "selectorCombinator",
    "selector",
    "property",
    "important",
    "styleDeclaration",
    "styleDeclarationList",
    "styleRule",
    "medium",
    "mediaList",
    "mediaRule",
    "pseudoPage",
    "pageRule",
    "unknownRuleParameterList",
    "unknownRuleBody",
    "unknownRule",
    "invalid",
  };
}
/* JavaCC - OriginalChecksum=3ae81ffe4fc4409228026bb007045eb5 (do not edit this line) */
