/* Generated By:JavaCC: Do not edit this line. ParserCSSCharsetDetectorTreeConstants.java Version 6.1_2 */
package com.helger.css.parser;

public interface ParserCSSCharsetDetectorTreeConstants
{
  public int JJTROOT = 0;


  public String[] jjtNodeName = {
    "Root",
  };
}
/* JavaCC - OriginalChecksum=d319f7a2c7d28421fed7a9843afd0836 (do not edit this line) */
